### ISSUE TITLE
Failed to migrate to 12.0

### ISSUE THREAD

**Issue by sergey-morenets** [MurhafSousli/ngx-highlightjs#293]
Hi

We failed to migrate ngx-highlightjs in our project from 10.0 to 12.0 because of the multiple errors in the console.
Please note, that new version added "language" property so the error may relate to this feature.

#### Reproduction

We couldn't reproduce this issue in StackBlitz (https://stackblitz.com/edit/ngx-highlightjs) because the changes were rebuilding too much (more than 15 mins) and probably stuck.

#### Expected Behavior

No issues should happen

#### Actual Behavior

If I use this line in the template: 

`<pre><code [highlight]="'int a'" language="java"></code></pre>`

I see an error in the console:

```
Error: Unknown language: "int a"
    at Object.f [as highlight] (global:scripts.js:10:4344)
    at _HighlightJS.<anonymous> (ngx-highlightjs.mjs:185:17)
    at Generator.next (<anonymous>)
```

If I use this line in the template:

`<pre><code [highlight]="'java'" language="java"></code></pre>`

I see this error in the console:

```
TypeError: t2.substr is not a function
    at Object.f [as highlight] (global:scripts.js:10:4593)
    at _HighlightJS.<anonymous> (ngx-highlightjs.mjs:185:17)
    at Generator.next (<anonymous>)
```

#### Environment

- Angular: 18.0.3
- ngx-highlightjs: 12.0.0
- Browser(s): Сhrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
Sometimes the stackblitz does that in Chome, try Firefox to reproduce it.

**Comment by sergey-morenets** [comment]
Hi @MurhafSousli 

We use Angular 19.0.5 now so we try to migrate to the ngx-highlightjs 13.0 and there's different error while rendering page with your component:

```
zone.js:2227 RuntimeError: NG0950: Input is required but no value is available yet. Find more at https://angular.dev/errors/NG0950
    at _Highlight.inputValueFn [as language] (core.mjs:98:13)
    at _Highlight.<anonymous> (ngx-highlightjs.mjs:400:22)
    at Generator.next (<anonymous>)

```

Please, note that we use standard module application without standalone components.

**Comment by MurhafSousli** [comment]
The error is clear, it says you need to provide a value for the language input when using the highlight directive!
